//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBoard
    {
        public int RID { get; set; }
        public string Username { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTimeOfMessage { get; set; }
    }
}
